export const balconylocalServices = [
  { href: "/localServices/balcony-safety-nets-anakapalle", text: "Near Me Balcony Safety Nets in Anakapalle" },
  { href: "/localServices/balcony-safety-nets-lankelapalem", text: "Near Me Balcony Safety Nets in Lankelapalem" },
  { href: "/localServices/balcony-safety-nets-kurmannapalem", text: "Near Me Balcony Safety Nets in Kurmannapalem" },
  { href: "/localServices/balcony-safety-nets-gajuwaka", text: "Near Me Balcony Safety Nets in Gajuwaka" },
  { href: "/localServices/balcony-safety-nets-autonagar", text: "Near Me Balcony Safety Nets in Autonagar" },
  { href: "/localServices/balcony-safety-nets-nad-visakhapatnam", text: "Near Me Balcony Safety Nets in NAD Visakhapatnam" },
  { href: "/localServices/balcony-safety-nets-sriharipuram", text: "Near Me Balcony Safety Nets in Sriharipuram" },
  { href: "/localServices/balcony-safety-nets-seethammadhara", text: "Near Me Balcony Safety Nets in Seethammadhara" },
  { href: "/localServices/balcony-safety-nets-dwarakanagar", text: "Near Me Balcony Safety Nets in Dwarakanagar" },
  { href: "/localServices/balcony-safety-nets-mvp-colony", text: "Near Me Balcony Safety Nets in MVP Colony" },
  { href: "/localServices/balcony-safety-nets-daba-gardens", text: "Near Me Balcony Safety Nets in Daba Gardens" },
  { href: "/localServices/balcony-safety-nets-madhurawada", text: "Near Me Balcony Safety Nets in Madhurawada" },
  { href: "/localServices/balcony-safety-nets-pedhagantyada", text: "Near Me Balcony Safety Nets in Pedhagantyada" },
  { href: "/localServices/balcony-safety-nets-rushikonda", text: "Near Me Balcony Safety Nets in Rushikonda" },
  { href: "/localServices/balcony-safety-nets-sujathanagar", text: "Near Me Balcony Safety Nets in Sujathanagar" },
  { href: "/localServices/balcony-safety-nets-anandapuram", text: "Near Me Balcony Safety Nets in Anandapuram" },
  { href: "/localServices/balcony-safety-nets-pendurti", text: "Near Me Balcony Safety Nets in Pendurti" },
  { href: "/localServices/balcony-safety-nets-gangavaram", text: "Near Me Balcony Safety Nets in Gangavaram" },
  { href: "/localServices/balcony-safety-nets-kancherapalem", text: "Near Me Balcony Safety Nets in Kancherapalem" },
  { href: "/localServices/balcony-safety-nets-iskathota", text: "Near Me Balcony Safety Nets in Iskathota" },
  { href: "/localServices/balcony-safety-nets-narasimhanagar", text: "Near Me Balcony Safety Nets in Narasimhanagar" },
  { href: "/localServices/balcony-safety-nets-gopalapatnam", text: "Near Me Balcony Safety Nets in Gopalapatnam" },
  { href: "/localServices/balcony-safety-nets-simhachalam", text: "Near Me Balcony Safety Nets in Simhachalam" },
  { href: "/localServices/balcony-safety-nets-durganagar", text: "Near Me Balcony Safety Nets in Durganagar" },
  { href: "/localServices/balcony-safety-nets-vishalakshinagar", text: "Near Me Balcony Safety Nets in Vishalakshi Nagar" },
  { href: "/localServices/balcony-safety-nets-subbavaram", text: "Near Me Balcony Safety Nets in Subbavaram" },
  { href: "/localServices/balcony-safety-nets-lakkavaram", text: "Near Me Balcony Safety Nets in Lakkavaram" },
  { href: "/localServices/balcony-safety-nets-bheemunipatnam", text: "Near Me Balcony Safety Nets in Bheemunipatnam" },
  { href: "/localServices/balcony-safety-nets-marripalem", text: "Near Me Balcony Safety Nets in Marripalem" },
  { href: "/localServices/balcony-safety-nets-aganampudi", text: "Near Me Balcony Safety Nets in Aganampudi" },
  { href: "/localServices/balcony-safety-nets-kasimkota", text: "Near Me Balcony Safety Nets in Kasimkota" },
  { href: "/localServices/balcony-safety-nets-yelamanchili", text: "Near Me Balcony Safety Nets in Yelamanchili" },
  { href: "/localServices/balcony-safety-nets-parawada", text: "Near Me Balcony Safety Nets in Parawada" },
  { href: "/localServices/balcony-safety-nets-payakaraopeta", text: "Near Me Balcony Safety Nets in Payakaraopeta" },
  { href: "/localServices/balcony-safety-nets-tuni", text: "Near Me Balcony Safety Nets in Tuni" },
  { href: "/localServices/balcony-safety-nets-annavaram", text: "Near Me Balcony Safety Nets in Annavaram" },
  { href: "/localServices/balcony-safety-nets-rajamahendravaram", text: "Near Me Balcony Safety Nets in Rajamahendravaram" },
  { href: "/localServices/balcony-safety-nets-achutapuram", text: "Near Me Balcony Safety Nets in Achutapuram" },
  { href: "/localServices/balcony-safety-nets-muralinagar", text: "Near Me Balcony Safety Nets in Muralinagar" },
  { href: "/localServices/balcony-safety-nets-purna-market", text: "Near Me Balcony Safety Nets in Purna Market" },
  { href: "/localServices/balcony-safety-nets-siripuram", text: "Near Me Balcony Safety Nets in Siripuram" },
];
export const invisibleGrillLocalService  = [
  { href: "/localService/invisible-grills-anakapalle", text: "Near Me Invisible Grills in Anakapalle" },
  { href: "/localService/invisible-grills-lankelapalem", text: "Near Me Invisible Grills in Lankelapalem" },
  { href: "/localService/invisible-grills-kurmannapalem", text: "Near Me Invisible Grills in Kurmannapalem" },
  { href: "/localService/invisible-grills-gajuwaka", text: "Near Me Invisible Grills in Gajuwaka" },
  { href: "/localService/invisible-grills-autonagar", text: "Near Me Invisible Grills in Autonagar" },
  { href: "/localService/invisible-grills-nad-visakhapatnam", text: "Near Me Invisible Grills in NAD Visakhapatnam" },
  { href: "/localService/invisible-grills-sriharipuram", text: "Near Me Invisible Grills in Sriharipuram" },
  { href: "/localService/invisible-grills-seethammadhara", text: "Near Me Invisible Grills in Seethammadhara" },
  { href: "/localService/invisible-grills-dwarakanagar", text: "Near Me Invisible Grills in Dwarakanagar" },
  { href: "/localService/invisible-grills-mvp-colony", text: "Near Me Invisible Grills in MVP Colony" },
  { href: "/localService/invisible-grills-daba-gardens", text: "Near Me Invisible Grills in Daba Gardens" },
  { href: "/localService/invisible-grills-madhurawada", text: "Near Me Invisible Grills in Madhurawada" },
  { href: "/localService/invisible-grills-pedhagantyada", text: "Near Me Invisible Grills in Pedhagantyada" },
  { href: "/localService/invisible-grills-rushikonda", text: "Near Me Invisible Grills in Rushikonda" },
  { href: "/localService/invisible-grills-sujathanagar", text: "Near Me Invisible Grills in Sujathanagar" },
  { href: "/localService/invisible-grills-anandapuram", text: "Near Me Invisible Grills in Anandapuram" },
  { href: "/localService/invisible-grills-pendurti", text: "Near Me Invisible Grills in Pendurti" },
  { href: "/localService/invisible-grills-gangavaram", text: "Near Me Invisible Grills in Gangavaram" },
  { href: "/localService/invisible-grills-kancherapalem", text: "Near Me Invisible Grills in Kancherapalem" },
  { href: "/localService/invisible-grills-iskathota", text: "Near Me Invisible Grills in Iskathota" },
  { href: "/localService/invisible-grills-narasimhanagar", text: "Near Me Invisible Grills in Narasimhanagar" },
  { href: "/localService/invisible-grills-gopalapatnam", text: "Near Me Invisible Grills in Gopalapatnam" },
  { href: "/localService/invisible-grills-simhachalam", text: "Near Me Invisible Grills in Simhachalam" },
  { href: "/localService/invisible-grills-durganagar", text: "Near Me Invisible Grills in Durganagar" },
  { href: "/localService/invisible-grills-vishalakshinagar", text: "Near Me Invisible Grills in Vishalakshi Nagar" },
  { href: "/localService/invisible-grills-subbavaram", text: "Near Me Invisible Grills in Subbavaram" },
  { href: "/localService/invisible-grills-lakkavaram", text: "Near Me Invisible Grills in Lakkavaram" },
  { href: "/localService/invisible-grills-bheemunipatnam", text: "Near Me Invisible Grills in Bheemunipatnam" },
  { href: "/localService/invisible-grills-marripalem", text: "Near Me Invisible Grills in Marripalem" },
  { href: "/localService/invisible-grills-aganampudi", text: "Near Me Invisible Grills in Aganampudi" },
  { href: "/localService/invisible-grills-kasimkota", text: "Near Me Invisible Grills in Kasimkota" },
  { href: "/localService/invisible-grills-yelamanchili", text: "Near Me Invisible Grills in Yelamanchili" },
  { href: "/localService/invisible-grills-parawada", text: "Near Me Invisible Grills in Parawada" },
  { href: "/localService/invisible-grills-payakaraopeta", text: "Near Me Invisible Grills in Payakaraopeta" },
  { href: "/localService/invisible-grills-tuni", text: "Near Me Invisible Grills in Tuni" },
  { href: "/localService/invisible-grills-annavaram", text: "Near Me Invisible Grills in Annavaram" },
  { href: "/localService/invisible-grills-rajamahendravaram", text: "Near Me Invisible Grills in Rajamahendravaram" },
  { href: "/localService/invisible-grills-achutapuram", text: "Near Me Invisible Grills in Achutapuram" },
  { href: "/localService/invisible-grills-muralinagar", text: "Near Me Invisible Grills in Muralinagar" },
  { href: "/localService/invisible-grills-purna-market", text: "Near Me Invisible Grills in Purna Market" },
  { href: "/localService/invisible-grills-siripuram", text: "Near Me Invisible Grills in Siripuram" },

]
export const nearMeBalconyServices = [

  /* ================= BALCONY SAFETY NETS ================= */

  { href: "/nearmeServices/balcony-safety-nets-near-me-anakapalle", text: "Near Me Balcony Safety Nets in Anakapalle" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-lankelapalem", text: "Near Me Balcony Safety Nets in Lankelapalem" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-kurmannapalem", text: "Near Me Balcony Safety Nets in Kurmannapalem" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-gajuwaka", text: "Near Me Balcony Safety Nets in Gajuwaka" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-autonagar", text: "Near Me Balcony Safety Nets in Autonagar" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-nad-visakhapatnam", text: "Near Me Balcony Safety Nets in NAD Visakhapatnam" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-sriharipuram", text: "Near Me Balcony Safety Nets in Sriharipuram" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-seethammadhara", text: "Near Me Balcony Safety Nets in Seethammadhara" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-dwarakanagar", text: "Near Me Balcony Safety Nets in Dwarakanagar" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-mvp-colony", text: "Near Me Balcony Safety Nets in MVP Colony" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-daba-gardens", text: "Near Me Balcony Safety Nets in Daba Gardens" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-madhurawada", text: "Near Me Balcony Safety Nets in Madhurawada" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-pedhagantyada", text: "Near Me Balcony Safety Nets in Pedhagantyada" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-rushikonda", text: "Near Me Balcony Safety Nets in Rushikonda" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-sujathanagar", text: "Near Me Balcony Safety Nets in Sujathanagar" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-anandapuram", text: "Near Me Balcony Safety Nets in Anandapuram" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-pendurti", text: "Near Me Balcony Safety Nets in Pendurti" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-gangavaram", text: "Near Me Balcony Safety Nets in Gangavaram" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-kancherapalem", text: "Near Me Balcony Safety Nets in Kancherapalem" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-iskathota", text: "Near Me Balcony Safety Nets in Iskathota" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-narasimhanagar", text: "Near Me Balcony Safety Nets in Narasimhanagar" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-gopalapatnam", text: "Near Me Balcony Safety Nets in Gopalapatnam" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-simhachalam", text: "Near Me Balcony Safety Nets in Simhachalam" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-durganagar", text: "Near Me Balcony Safety Nets in Durganagar" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-vishalakshinagar", text: "Near Me Balcony Safety Nets in Vishalakshi Nagar" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-subbavaram", text: "Near Me Balcony Safety Nets in Subbavaram" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-lakkavaram", text: "Near Me Balcony Safety Nets in Lakkavaram" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-bheemunipatnam", text: "Near Me Balcony Safety Nets in Bheemunipatnam" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-marripalem", text: "Near Me Balcony Safety Nets in Marripalem" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-aganampudi", text: "Near Me Balcony Safety Nets in Aganampudi" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-kasimkota", text: "Near Me Balcony Safety Nets in Kasimkota" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-yelamanchili", text: "Near Me Balcony Safety Nets in Yelamanchili" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-parawada", text: "Near Me Balcony Safety Nets in Parawada" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-payakaraopeta", text: "Near Me Balcony Safety Nets in Payakaraopeta" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-tuni", text: "Near Me Balcony Safety Nets in Tuni" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-annavaram", text: "Near Me Balcony Safety Nets in Annavaram" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-rajamahendravaram", text: "Near Me Balcony Safety Nets in Rajamahendravaram" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-achutapuram", text: "Near Me Balcony Safety Nets in Achutapuram" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-muralinagar", text: "Near Me Balcony Safety Nets in Muralinagar" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-purna-market", text: "Near Me Balcony Safety Nets in Purna Market" },
  { href: "/nearmeServices/balcony-safety-nets-near-me-siripuram", text: "Near Me Balcony Safety Nets in Siripuram" },

]
  export const nearMeInvisibleServices = [
  /* ================= INVISIBLE GRILLS ================= */

  { href: "/nearmeServices/invisible-grills-near-me-anakapalle", text: "Near Me Invisible Grills in Anakapalle" },
  { href: "/nearmeServices/invisible-grills-near-me-lankelapalem", text: "Near Me Invisible Grills in Lankelapalem" },
  { href: "/nearmeServices/invisible-grills-near-me-kurmannapalem", text: "Near Me Invisible Grills in Kurmannapalem" },
  { href: "/nearmeServices/invisible-grills-near-me-gajuwaka", text: "Near Me Invisible Grills in Gajuwaka" },
  { href: "/nearmeServices/invisible-grills-near-me-autonagar", text: "Near Me Invisible Grills in Autonagar" },
  { href: "/nearmeServices/invisible-grills-near-me-nad-visakhapatnam", text: "Near Me Invisible Grills in NAD Visakhapatnam" },
  { href: "/nearmeServices/invisible-grills-near-me-sriharipuram", text: "Near Me Invisible Grills in Sriharipuram" },
  { href: "/nearmeServices/invisible-grills-near-me-seethammadhara", text: "Near Me Invisible Grills in Seethammadhara" },
  { href: "/nearmeServices/invisible-grills-near-me-dwarakanagar", text: "Near Me Invisible Grills in Dwarakanagar" },
  { href: "/nearmeServices/invisible-grills-near-me-mvp-colony", text: "Near Me Invisible Grills in MVP Colony" },
  { href: "/nearmeServices/invisible-grills-near-me-daba-gardens", text: "Near Me Invisible Grills in Daba Gardens" },
  { href: "/nearmeServices/invisible-grills-near-me-madhurawada", text: "Near Me Invisible Grills in Madhurawada" },
  { href: "/nearmeServices/invisible-grills-near-me-pedhagantyada", text: "Near Me Invisible Grills in Pedhagantyada" },
  { href: "/nearmeServices/invisible-grills-near-me-rushikonda", text: "Near Me Invisible Grills in Rushikonda" },
  { href: "/nearmeServices/invisible-grills-near-me-sujathanagar", text: "Near Me Invisible Grills in Sujathanagar" },
  { href: "/nearmeServices/invisible-grills-near-me-anandapuram", text: "Near Me Invisible Grills in Anandapuram" },
  { href: "/nearmeServices/invisible-grills-near-me-pendurti", text: "Near Me Invisible Grills in Pendurti" },
  { href: "/nearmeServices/invisible-grills-near-me-gangavaram", text: "Near Me Invisible Grills in Gangavaram" },
  { href: "/nearmeServices/invisible-grills-near-me-kancherapalem", text: "Near Me Invisible Grills in Kancherapalem" },
  { href: "/nearmeServices/invisible-grills-near-me-iskathota", text: "Near Me Invisible Grills in Iskathota" },
  { href: "/nearmeServices/invisible-grills-near-me-narasimhanagar", text: "Near Me Invisible Grills in Narasimhanagar" },
  { href: "/nearmeServices/invisible-grills-near-me-gopalapatnam", text: "Near Me Invisible Grills in Gopalapatnam" },
  { href: "/nearmeServices/invisible-grills-near-me-simhachalam", text: "Near Me Invisible Grills in Simhachalam" },
  { href: "/nearmeServices/invisible-grills-near-me-durganagar", text: "Near Me Invisible Grills in Durganagar" },
  { href: "/nearmeServices/invisible-grills-near-me-vishalakshinagar", text: "Near Me Invisible Grills in Vishalakshi Nagar" },
  { href: "/nearmeServices/invisible-grills-near-me-subbavaram", text: "Near Me Invisible Grills in Subbavaram" },
  { href: "/nearmeServices/invisible-grills-near-me-lakkavaram", text: "Near Me Invisible Grills in Lakkavaram" },
  { href: "/nearmeServices/invisible-grills-near-me-bheemunipatnam", text: "Near Me Invisible Grills in Bheemunipatnam" },
  { href: "/nearmeServices/invisible-grills-near-me-marripalem", text: "Near Me Invisible Grills in Marripalem" },
  { href: "/nearmeServices/invisible-grills-near-me-aganampudi", text: "Near Me Invisible Grills in Aganampudi" },
  { href: "/nearmeServices/invisible-grills-near-me-kasimkota", text: "Near Me Invisible Grills in Kasimkota" },
  { href: "/nearmeServices/invisible-grills-near-me-yelamanchili", text: "Near Me Invisible Grills in Yelamanchili" },
  { href: "/nearmeServices/invisible-grills-near-me-parawada", text: "Near Me Invisible Grills in Parawada" },
  { href: "/nearmeServices/invisible-grills-near-me-payakaraopeta", text: "Near Me Invisible Grills in Payakaraopeta" },
  { href: "/nearmeServices/invisible-grills-near-me-tuni", text: "Near Me Invisible Grills in Tuni" },
  { href: "/nearmeServices/invisible-grills-near-me-annavaram", text: "Near Me Invisible Grills in Annavaram" },
  { href: "/nearmeServices/invisible-grills-near-me-rajamahendravaram", text: "Near Me Invisible Grills in Rajamahendravaram" },
  { href: "/nearmeServices/invisible-grills-near-me-achutapuram", text: "Near Me Invisible Grills in Achutapuram" },
  { href: "/nearmeServices/invisible-grills-near-me-muralinagar", text: "Near Me Invisible Grills in Muralinagar" },
  { href: "/nearmeServices/invisible-grills-near-me-purna-market", text: "Near Me Invisible Grills in Purna Market" },
  { href: "/nearmeServices/invisible-grills-near-me-siripuram", text: "Near Me Invisible Grills in Siripuram" },

];